apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: dev5-rbac-editor
  namespace: test-product-dev5
rules:
  - apiGroups:
      - "*"
    resources:
      - "*"
    verbs:
      - create
      - delete
      - update
      - get
      - list
      - watch
      - patch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: oidc-dev5-rbac-editor
  namespace: test-product-dev5
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: dev5-rbac-editor
subjects:
  - apiGroup: rbac.authorization.k8s.io
    kind: Group
    name: CPaaS-stage-test-product-editor
